---
# =====================
#    Config Version
# =====================
# For internal use only, do not exchange!!

config-version: 1.0.0

# =====================
#     Join Message 
# =====================
# Message on Player Join in the Server
# You can use tags {player} for name & {line} for new line

join-message: false
popup: false 
message: "Welcome to server {player}"

# =====================
#       Join Sound 
# =====================
# Sound played when player join in server

join-sound: false 
join-sound-name: "random.pop"

# =====================
#       Quit Sound 
# =====================
# Sound played when player quit from the server

quit-sound: false 
quit-sound-name: "random.pop"

# =====================
#       Quit Clear 
# =====================
# Events to clear certains player's inventory onQuit

quit-clear: false
clear-normal-inventory: false
clear-armor-inventory: false
clear-effects: false

# =====================
#      Anti Break
# =====================
# Event to prevent players break blocks in certain worlds

anti-break: false
anti-break-alert-message: false
anti-break-message: "§cYou can't break blocks here!"

anti-break-worlds: ["Lobby", "Lobby1"]

# =====================
#      Anti Place
# =====================
# Event to prevent players break blocks in certain worlds

anti-place: false
anti-place-alert-message: false
anti-place-message: "§cYou can't place blocks here!"

anti-place-worlds: ["Lobby", "Lobby1"]

# =====================
#      Anti Place
# =====================
# Event to prevent players drop items in certain worlds

anti-drop: false
anti-drop-alert-message: false
anti-drop-message-popup: false
anti-drop-message: "§cYou can't drop items here!"

anti-drop-worlds ["Lobby", "KitPvP"]
...