# =====================
#     Join Message 
# =====================
# Message on Player Join in the Server
# You can use tags {player} for name & {line} for new line

join-message: false
popup: false 
message: "Welcome to server {player}"

# =====================
#       Join Sound 
# =====================
# Sound played when player join in server

join-sound: false 
join-sound-name: "random.pop"

# =====================
#       Quit Sound 
# =====================
# Sound played when player quit from the server

quit-sound: false 
quit-sound-name: "random.pop"

# =====================
#       Quit Clear 
# =====================
# Events to clear certains player's inventory onQuit

quit-clear: false
clear-normal-inventory: false
clear-armor-inventory: false
clear-effects: false

